### ISSUE TITLE
Problem to convert Dives from Suunto Stinger, Dive Manager 3.1.0, SDE

### ISSUE THREAD

**Issue by Ralle04** [nradov/SdeToFit#2]
Hello,
I have tried to convert my Dives from Suunto Dive Manager 3.1.0 logged with a Suunto Stinger in the Fit-format for Garmin connect.

I received the following error:

c:\Users\rk.NBG\Documents\DiveTool>java.exe -cp %CLASSPATH%;SdeToFit-1.0-SNAPSHOT.jar com.github.nradov.sdetofit.SdeToFit c:\Users\rk.NBG\Documents\DiveTool\Input\Divelogs.SDE c:\Users\rk.NBG\Documents\DiveTool\Output
Converting dive log: "0.xml"
Exception in thread "main" java.lang.NumberFormatException: For input string: "20,7"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
        at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.base/java.lang.Float.parseFloat(Float.java:556)
        at com.github.nradov.sdetofit.suunto.SuuntoXml.<init>(SuuntoXml.java:72)
        at com.github.nradov.sdetofit.suunto.SuuntoSde.<init>(SuuntoSde.java:46)
        at com.github.nradov.sdetofit.DivesSourceFactory.create(DivesSourceFactory.java:55)
        at com.github.nradov.sdetofit.SdeToFit.convert(SdeToFit.java:72)
        at com.github.nradov.sdetofit.SdeToFit.main(SdeToFit.java:68)

what's wrong, can someone help

[Divelogs.zip](https://github.com/nradov/SdeToFit/files/11712086/Divelogs.zip)

in the appendix are 5 dives

**Comment by nradov** [comment]
It looks like this defect is a result of Suunto failing to follow the XML Schema standard for the [decimal](https://www.w3.org/TR/xmlschema-2/#decimal) data type. In XML files the decimal separator is always supposed to be a period, but it looks like here Suunto Dive Manager picked up the OS localization settings and used a comma as the separator instead. So, shame on them for failing to follow industry standards (and for not documenting their file format).
It should be fairly easy to fix this defect by replacing the comma with a period before parsing it as a float.

**Comment by nradov** [comment]
I still haven't had time to work on this but you might be able to work around the defect. Try changing your OS localization settings to use "." instead of "," as the decimal separator. Then export the logs from SDM again. Hopefully that will generate the correct XML files.

**Comment by Ralle04** [comment]
Hello Nick,

I have changed the localization settings from "," to "." as separator and exported the Dives again.
Now the generated file was all right converted.

Many thanks!
